services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - voxa_network

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - voxa_network

networks:
  voxa_network:
    external: true